project:
  type: website
  output-dir: docs
  resources: 
    - styles.css 
    - _beforebody.html
    - _footer.html
    - 2026/figures
    - "2026/files/*"
    - 2026/files
  render: 
    - 2026/*.qmd

website:
  title: "Iberian Prion Meeting 2026"
  navbar:
    title: "Iberian Prion Meeting 2026"
    href: "/2026/"
    left:
      - href: 2026/index.qmd
        text: "Home 2026"
      - href: 2026/abstracts.qmd
        text: "Abstracts"
      - href: 2026/committee.qmd
        text: "Committee"
      - href: 2026/programme.qmd
        text: "Programme"
      - href: 2026/registration.qmd
        text: "Registration"
      - href: 2026/venue.qmd
        text: "Venue"
      - href: 2026/sponsors.qmd
        text: "Sponsors"
      - href: 2026/contact.qmd
        text: "Contact"

format:
  html:
    css: styles.css
    include-before-body: _beforebody.html
    include-after-body: _footer.html
